### ISSUE TITLE
Arduino Leonardo ETH hangs using this library

### ISSUE THREAD

**Issue by maziu** [graetz23/coolSAA1064#1]
Hi,
Arduino Leonardo hangs when using this library if SAA1064 object is created as global object. Reason is that Wire.begin() is called before Arduino setup() is called. 

Fix: add SAA1064.begin() method and move Wire.begin() to this function. Call SAA1064.begin() in Arduino's setup() function. Then it works fine.

Thanks for cool library!

**Comment by cscheiblich** [comment]
Thanks for the issue and the hint how to solve!

Going to change that ..

Chris

**Comment by graetz23** [comment]
.. took it's time but there's a setup method now, doing exactly what you suggested.

cheers
Christian
